version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    environment:
      - MONGO_URI=mongodb+srv://hatemdridi:ngmfVxVlGkqA8YNd@cluster0.u5ksf.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "9000:9000"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
